# Generated by Django 4.0.5 on 2022-08-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(height_field=300, upload_to='images', verbose_name='Upload image here', width_field=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
